name: "Terraform_dev"
permissions:
  id-token: write
  contents: read
on: 
  workflow_dispatch:
  #pull_request:
   # branches:
      #- main
  #push:
   # branches:
     # - main
  

  
jobs:
  Terraform_plan:
    name: Terraform_Plan
    runs-on: ketan-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: d8f042c7-16f3-4328-9837-ae52c36be795
          tenant-id: 34969ee9-a0d2-43d0-bf8a-b3bd43c55eea
          subscription-id: 98473d5b-c639-404e-9bf2-91559fe65ff8

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive
        continue-on-error: true
        working-directory: todoapp-infra
      
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: todoapp-infra
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: todoapp-infra
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true 
        working-directory: todoapp-infra
        
  Terraform_Apply:
    name: Terraform_Apply
    if: github.ref == 'refs/heads/main'
    runs-on: ketan-runner
    needs: Terraform_plan
    environment: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: d8f042c7-16f3-4328-9837-ae52c36be795
          tenant-id: 34969ee9-a0d2-43d0-bf8a-b3bd43c55eea
          subscription-id: 98473d5b-c639-404e-9bf2-91559fe65ff8

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: todoapp-infra

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: todoapp-infra
  
          
      
  
          
