name: "Terraform_dev"
permissions:
  id-token:write
  contents:read
on: 
  push:
    branches:
      - 'feature/**'
      - 'main'
      - 'hotfix/**'

  
jobs:
  Terraform_plan:
    name: Terraform
    runs-on: ketan-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 043a92c7-69b2-4318-9276-ff7ffafd2f1f

          tenant-id: af734fcf-6a49-4af5-8ec9-51df7466b2c5

          subscription-id: 95a90f4b-7e15-47ba-95ab-0d52bac078e4
  
          
      
  
          
